name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # target: your-target(optional if you have/need one)
          # entryPoint: "./"
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUI_DAPP_KIT_THEME_CREATOR }}
          # projectId: sui-dapp-kit-theme-creator
          channelId: live
          projectId: '${{ env.PROJECT_ID }}'
