name: Deploy to Firebase Hosting on Push
on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # target: your-target(optional if you have/need one)
          entryPoint: "./dist"
          firebaseServiceAccount: '${{ env.FIREBASE_SERVICE_ACCOUNT }}'
          # channelId: live
          projectId: '${{ env.PROJECT_ID }}'
